export default {
items:
[
        {
            itemId: '1.1',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 24.3,
            valorunit: 4.0,
            valortotal: 1.0,
        },
        {
            item: '1.2',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 37.2,
            valorunit: 4.3,
            valortotal: 1.0,
        },
        {
            item: '1.3',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 23.2,
            valorunit: 6.0,
            valortotal: 7.5,
        },
        {
            item: '1.4',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 67.3,
            valorunit: 4.3,
            valortotal: 8.0,
        },
        {
            item: '2.1',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 49.0,
            valorunit: 3.9,
            valortotal: 16.2,
        },
        {
            item: '2.2',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 94.0,
            valorunit: 0.0,
            valortotal: 120.2,
        },
        {
            item: '2.3',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 98.0,
            valorunit: 0.0,
            valortotal: 2.0,
        },
        {
            item: '3.1',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 87.8,
            valorunit: 6.5,
            valortotal: 45.0,
        },
        {
            item: '3.2',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 51.8,
            valorunit: 4.9,
            valortotal: 22.0,
        },
        {
            item: '3.3',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 65.8,
            valorunit: 7.0,
            valortotal: 6.0,
        },
    ]
}